---
title: "Class 4 Participation"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    storyboard: TRUE
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(htmltools)
library(shinydashboard)
library(ggplot2)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# Include *** for commentary to appear; anything beneath those will become comments.
DT::datatable(mtcars, options = list(
  bPaginate = FALSE)
  )

ggplot(data = mtcars, mapping = aes(x = mpg, y = wt)) +
  geom_point() + 
  coord_flip()

# As weight goes up, miles per gallon does down.

```

Row {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
# Let's look at mpg vs horsepower

ggplot(data = mtcars, mapping = aes(x = mpg, y = hp)) +
  geom_point() + 
  coord_flip()

```

### Chart C

```{r}
# hp versus number of cylinders

ggplot(data = mtcars, mapping = aes(x = cyl, y = hp)) +
  geom_point()

```

